package techprosolution.chatdemo.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import techprosolution.chatdemo.dao.Users;
import techprosolution.chatdemo.dao.Messages;

import techprosolution.chatdemo.dao.UsersDao;
import techprosolution.chatdemo.dao.MessagesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig usersDaoConfig;
    private final DaoConfig messagesDaoConfig;

    private final UsersDao usersDao;
    private final MessagesDao messagesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        usersDaoConfig = daoConfigMap.get(UsersDao.class).clone();
        usersDaoConfig.initIdentityScope(type);

        messagesDaoConfig = daoConfigMap.get(MessagesDao.class).clone();
        messagesDaoConfig.initIdentityScope(type);

        usersDao = new UsersDao(usersDaoConfig, this);
        messagesDao = new MessagesDao(messagesDaoConfig, this);

        registerDao(Users.class, usersDao);
        registerDao(Messages.class, messagesDao);
    }
    
    public void clear() {
        usersDaoConfig.getIdentityScope().clear();
        messagesDaoConfig.getIdentityScope().clear();
    }

    public UsersDao getUsersDao() {
        return usersDao;
    }

    public MessagesDao getMessagesDao() {
        return messagesDao;
    }

}
